# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-EmpireTheatres
version:      0.04
version_from: lib/WWW/EmpireTheatres.pm
installdirs:  site
requires:
    Class::Accessor:               0
    HTML::TokeParser::Simple:      0
    Test::MockModule:              0
    Test::More:                    0
    URI:                           0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
